-- ======================================================
-- Banking Management System - Oracle Schema
-- Author: Sudip Bera
-- Version: 1.0
-- ======================================================

-- Optional: Drop old tables (for development reset)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOAN_PAYMENT CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE LOAN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TRANSACTION CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE BRANCH CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ======================================================
-- 1️ CUSTOMER TABLE
-- ======================================================
CREATE TABLE CUSTOMER (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(100) NOT NULL,
  dob DATE,
  address VARCHAR2(200),
  phone VARCHAR2(15) UNIQUE,
  email VARCHAR2(100) UNIQUE
);

-- ======================================================
-- 2️ BRANCH TABLE
-- ======================================================
CREATE TABLE BRANCH (
  branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_name VARCHAR2(100) NOT NULL,
  location VARCHAR2(100)
);

-- ======================================================
-- 3️ EMPLOYEE TABLE
-- ======================================================
CREATE TABLE EMPLOYEE (
  emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_name VARCHAR2(100) NOT NULL,
  role VARCHAR2(50),
  branch_id NUMBER,
  hire_date DATE DEFAULT SYSDATE,
  salary NUMBER(10,2),
  CONSTRAINT fk_emp_branch FOREIGN KEY (branch_id) REFERENCES BRANCH(branch_id)
);

-- ======================================================
-- 4️ ACCOUNT TABLE
-- ======================================================
CREATE TABLE ACCOUNT (
  account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  branch_id NUMBER NOT NULL,
  account_type VARCHAR2(50) CHECK (account_type IN ('Savings','Current','Fixed Deposit')),
  balance NUMBER(12,2) DEFAULT 0,
  open_date DATE DEFAULT SYSDATE,
  status VARCHAR2(20) DEFAULT 'Active',
  CONSTRAINT fk_acc_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
  CONSTRAINT fk_acc_branch FOREIGN KEY (branch_id) REFERENCES BRANCH(branch_id)
);

-- ======================================================
-- 5️ TRANSACTION TABLE
-- ======================================================
CREATE TABLE TRANSACTION (
  txn_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id NUMBER NOT NULL,
  txn_type VARCHAR2(20) CHECK (txn_type IN ('Deposit','Withdrawal','Transfer')),
  amount NUMBER(10,2) CHECK (amount > 0),
  txn_date DATE DEFAULT SYSDATE,
  description VARCHAR2(200),
  CONSTRAINT fk_txn_account FOREIGN KEY (account_id) REFERENCES ACCOUNT(account_id)
);

-- ======================================================
-- 6️ LOAN TABLE
-- ======================================================
CREATE TABLE LOAN (
  loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  branch_id NUMBER NOT NULL,
  loan_type VARCHAR2(50) CHECK (loan_type IN ('Home Loan','Car Loan','Education Loan','Personal Loan')),
  amount NUMBER(12,2),
  issue_date DATE DEFAULT SYSDATE,
  due_date DATE,
  status VARCHAR2(20) DEFAULT 'Ongoing',
  CONSTRAINT fk_loan_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
  CONSTRAINT fk_loan_branch FOREIGN KEY (branch_id) REFERENCES BRANCH(branch_id)
);

-- ======================================================
-- 7️ LOAN_PAYMENT TABLE
-- ======================================================
CREATE TABLE LOAN_PAYMENT (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id NUMBER NOT NULL,
  payment_date DATE DEFAULT SYSDATE,
  amount NUMBER(10,2),
  payment_method VARCHAR2(20) CHECK (payment_method IN ('Cash','NEFT','UPI','Cheque')),
  CONSTRAINT fk_payment_loan FOREIGN KEY (loan_id) REFERENCES LOAN(loan_id)
);

-- ======================================================
--  INDEXES
-- ======================================================
CREATE INDEX idx_customer_name ON CUSTOMER(full_name);
CREATE INDEX idx_account_customer ON ACCOUNT(customer_id);
CREATE INDEX idx_transaction_date ON TRANSACTION(txn_date);
CREATE INDEX idx_loan_customer ON LOAN(customer_id);

-- ======================================================
-- 📊 VIEWS
-- ======================================================
CREATE OR REPLACE VIEW CUSTOMER_ACCOUNTS AS
SELECT c.full_name, a.account_id, a.account_type, a.balance, a.status
FROM CUSTOMER c
JOIN ACCOUNT a ON c.customer_id = a.customer_id;

-- ======================================================
-- ✅ SAMPLE DATA (Optional)
-- ======================================================
INSERT INTO BRANCH (branch_name, location) VALUES ('Kolkata Main', 'Kolkata');
INSERT INTO BRANCH (branch_name, location) VALUES ('Mumbai Central', 'Mumbai');
INSERT INTO CUSTOMER (full_name, dob, address, phone, email)
VALUES ('Ravi Sharma', TO_DATE('1990-05-12', 'YYYY-MM-DD'), 'Kolkata, India', '9876543210', 'ravi@example.com');
INSERT INTO CUSTOMER (full_name, dob, address, phone, email)
VALUES ('Priya Das', TO_DATE('1995-09-22', 'YYYY-MM-DD'), 'Mumbai, India', '9123456780', 'priya@example.com');

INSERT INTO ACCOUNT (customer_id, branch_id, account_type, balance)
VALUES (1, 1, 'Savings', 25000);
INSERT INTO ACCOUNT (customer_id, branch_id, account_type, balance)
VALUES (2, 2, 'Current', 80000);

COMMIT;
